title: "Ortho-Fuse: Orthomosaic Generation for Sparse high resolution AI-driven health maps through optical flow estimation"
description: >-
  A research project focused on generating orthomosaics for sparse high resolution 
  AI-driven health maps using optical flow estimation techniques.

baseurl: ""
url: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

permalink: /:categories/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/