title: "Ortho-Fuse: Orthomosaic Generation for Sparse High-Resolution AI-driven Health Maps through Optical Flow Estimation"
description: >-
  An optical flow-based framework that enables reliable orthomosaic generation with reduced overlap requirements for agricultural monitoring applications.

baseurl: ""
url: ""

# Use a simple, clean theme
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/